# Generated by Django 6.0.7 on 2026-09-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_counted_views_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': 'POST', 'verbose_name_plural': 'POSTS'},
        ),
    ]
